CREATE DATABASE db_notas
GO
USE db_notas
GO

CREATE TABLE [Notas] 
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[Persona] NVARCHAR(150) NOT NULL,
	[Nota1] DECIMAL(10, 2) NOT NULL DEFAULT 0,
	[Nota2] DECIMAL(10, 2) NOT NULL DEFAULT 0,
	[Nota3] DECIMAL(10, 2) NOT NULL DEFAULT 0,
	[Nota4] DECIMAL(10, 2) NOT NULL DEFAULT 0,
	[Nota5] DECIMAL(10, 2) NOT NULL DEFAULT 0,
	[Final] DECIMAL(10, 2) NOT NULL DEFAULT 0,
	[Fecha] SMALLDATETIME NOT NULL DEFAULT GETDATE(),
);

INSERT INTO [Notas] ([Persona],[Nota1],[Nota2],[Nota3],[Nota4],[Nota5],[Final],[Fecha])
VALUES ('Pepito Perez', 2.3, 4.5, 3.5, 1.4, 5, 0, GETDATE());

SELECT * FROM [Notas];